In [2]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.neural_network import MLPClassifier

from sklearn.tree import DecisionTreeClassifier
from sklearn.tree import export_graphviz
from sklearn import tree
from sklearn.datasets import load_wine
from IPython.display import SVG
from IPython.display import display

from graphviz import Source
from ipywidgets import interactive

from sklearn import metrics
from sklearn.preprocessing import StandardScaler

In [3]:
df1_train = pd.read_pickle("./df1_reduced_train.pkl")
df1_test  = pd.read_pickle("./df1_reduced_test.pkl")

print(str(len(df1_train))+" "+str(len(df1_test)))
df1_test.head(3)

2661 672


account length  area code  international plan  \
phone number                                                  
0                      128.0      415.0                 0.0   
1                      141.0      415.0                 1.0   
2                       85.0      408.0                 0.0   

              number vmail messages  total day calls  total day charge  \
phone number                                                             
0                              25.0            110.0             45.07   
1                              37.0             84.0             43.96   
2                              27.0            139.0             33.39   

              total eve calls  total eve charge  total night calls  \
phone number                                                         
0                        99.0             16.78               91.0   
1                       111.0             18.87               97.0   
2                        90.0             23.88               75.0   

              total night charge  total intl calls  total intl charge  \
phone number                                                            
0                          11.01               3.0               2.70   
1                          14.69               5.0               3.02   
2                           4.02               4.0               3.73   

              customer service calls  churn  
phone number                                 
0                                1.0    0.0  
1                                0.0    0.0  
2                                1.0    0.0

In [25]:
def get_data():
    X_train       = df1_train.iloc[:,:-1]
    y_train       = df1_train.iloc[:,-1:]
    X_test        = df1_test.iloc[:,:-1]
    y_test        = df1_test.iloc[:,-1:]
    
    scaler        = StandardScaler()
    scaler.fit(X_train)                                       
    X_train       = scaler.transform(X_train)
    X_test        = scaler.transform(X_test)
    
    return X_train, y_train, X_test, y_test

In [29]:
def run_decission_tree(criteria, split_type, max_depth, min_split, min_leaf):
    X_train, y_train, X_test, y_test = get_data()

    decision_tree = DecisionTreeClassifier(criterion = criteria, splitter = split_type, max_depth = max_depth, 
                                       min_samples_split = min_split , min_samples_leaf = min_leaf)
    decision_tree.fit(X_train, y_train)
    
    y_pred_train       = decision_tree.predict(X_train)
    y_pred_test        = decision_tree.predict(X_test)                
    
    print("Accuracy   :", metrics.accuracy_score(y_test, y_pred_test))
    return y_pred_train, y_pred_test

In [ ]:
1 0.91369047619
2 0.922619047619
3 0.925595238095
4 0.924107142857
5 0.924107142857
6 0.91369047619
7 0.91369047619
8 0.922619047619
9 0.921130952381
10 
11 0.927083333333
12 0.936011904762 *********
13


16 0.931547619048


22 0.93005952381

25,26,53 0.9375

In [106]:
def run_dnn(_solver, _alpha, _layers, _max_iter):
    X_train, y_train, X_test, y_test = get_data()
    
    nn_clf = MLPClassifier(solver=_solver, alpha=_alpha, hidden_layer_sizes=_layers, max_iter=_max_iter, verbose=False, 
                          warm_start=False, random_state=25)
    nn_clf.fit(X_train, y_train) 
    
    y_pred_train       = nn_clf.predict(X_train)
    y_pred_test        = nn_clf.predict(X_test)  
    
    print("Accuracy   :", metrics.accuracy_score(y_test, y_pred_test))
    return y_pred_train, y_pred_test
run_dnn('adam',0.000001, (12,12,12,6), 500)

F:\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:912: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy   : 0.9375


(array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  1.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
      

In [30]:
run_decission_tree("entropy", "best", None, 0.01, 0.01)

Accuracy   : 0.918154761905


(array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
         0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
      

In [34]:
run_dnn('adam',0.000001, (12,12,12,6), 500)

F:\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:912: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy   : 0.921130952381


(array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
 array([ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,
         0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,  0.,  1.,  0.,
         0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,
         1.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
      

In [40]:
def run_parallel_model():
    run_decission_tree("entropy", "best", None, 0.01, 0.01)
    print('x')
    run_dnn('adam',0.000001, (12,12,12,6), 500)
    return
run_parallel_model()

Accuracy   : 0.918154761905
x


F:\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:912: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Accuracy   : 0.91369047619
